---
title: "Fast talk plots"
author: "Qianhui"
date: "03/12/2019"
output: html_document
---

# load packages needed
```{r pkgs, message=FALSE, warning=FALSE, results="hide"}

pkgs <- c("tidyverse", "plyranges", "magrittr", "doParallel", "ggplot2", "ggpubr", "RColorBrewer", 
          "gridExtra", "here", "mclust", "ggedit")

# require(x) #library function is better for loding packages than require function
lapply(pkgs, library, character.only = TRUE)

```


# load clean data needed
## Data for PPT plot 1
```{r, message=FALSE, warning=FALSE}
# PCAs
PCA_Placenta_M <- readRDS(file  = here("cleanData/PCA_all.Rds"))

PCA408plot <- readRDS(file = here("cleanData/T1TermSamples_PCA408samples.rds"))

PCAT1T2Termplot <- readRDS(file = here("cleanData/PCAallplot.rds"))

# outlierDim1Plot_all <- readRDS(file = here("cleanData/outlierDim1Plot_all.rds"))

load(file = here("cleanData/GEO_phenotypes_add10.RData"))

NormBMlist <- readRDS(file = here("cleanData/NormBMlist_300k.rds"))
NormMAll <- NormBMlist$NormMAll
table(colnames(NormMAll) %in% GEO_phenotypes$Sample_name)
rm(NormBMlist, GEOmeta)

GEO_phenotypes_ewastoolPurityCheck_output <- read_csv(file =  here("cleanData/GEO_phenotypes_ewastoolPurityCheck_output.csv"))

EwastoolOutlierName <- GEO_phenotypes_ewastoolPurityCheck_output[GEO_phenotypes_ewastoolPurityCheck_output$log_odds> -4,]$Sample_name
```

## Data for PPT plot 2
```{r}

placenta_beta_dim1Top2perc.df_all <- readRDS(file = here("cleanData/placenta_beta_dim1Top2perc.df_all.rds"))

# Data for Gviz plot
# PMDs_hg19 <- readRDS(file = here("cleanData/Placenta9-PMDpublished_hg19GR.unlisted.rds"))
# ICRsGR <- readRDS(file =here("cleanData/ICRsGR.rds"))

# for ICR/PMD violin plot
AllPMDsMeanViolinPlot <- readRDS(file = here("cleanData/AllPMDsMeanViolinPlot.rds"))
allICRsViolinPlot <- readRDS(file = here("cleanData/allICRsViolinPlot.rds"))

```


# PPT plot 1A

```{r}
theme_set(theme_pubr())

PCA408plot$layers[[1]]$mapping$shape <- NULL
PCA408plot_label <- PCA408plot+
  geom_text(aes(x=155 , y=-500, label="Q3+1.5*IQR"), vjust=-0.4, hjust=0, size=2, colour="blue") +
  geom_text(aes(x=320 , y=-600, label="Q3+3*IQR"), vjust=-0.4, hjust=0, size=2, colour="blue") +
  # geom_point(stroke =2)+
  theme(text = element_text(size=9),
        legend.title=element_text(size=7),
        legend.text=element_text(size=6),
        legend.key.size = unit(3,"mm"),
        axis.text.x =element_text(size=9, colour = "black"),
        axis.text.y =element_text(size=9, colour = "black"),
        legend.position="top")+
  guides(colour = guide_legend(title.position="top", nrow = 3,
                               title.hjust = 0.5))

PCA408plot_label$layers[[1]]$aes_params$size <- 2


print(PCA408plot_label)

```

# PPT plot 1B

```{r}

Matched_pd <- GEO_phenotypes[match(colnames(NormMAll), GEO_phenotypes$Sample_name),]

df <- PCA_Placenta_M$ind$coord %>% as.data.frame() %>% rownames_to_column(var="Sample_name") %>% 
  left_join(Matched_pd, by="Sample_name") %>% column_to_rownames(var="Sample_name")

a1 <- mclust::Mclust(df[,c("Dim.1","Dim.2")],2) #for 2 groups
table(a1$classification,df$Sample)

# plot mclust result supl
df$class <- a1$classification
df$percent <- a1$z[,2]

df$Sample2 <- str_replace_all(df$Sample, "Umbilical cord blood", "Cord blood")
df$ewastools <- ifelse(rownames(df)%in%EwastoolOutlierName, "Yes", "No") #Contaminated samples\n(ewastools)

PCAclassPlot <- df %>%
  ggplot(aes(Dim.1, Dim.2)) +
  geom_point(aes(shape = Sample2, col=as.factor(class)), size = 2)+ #, alpha = percent
  scale_shape_manual(name="Samples", values=c(0, 5, 12, 2, 3, 1))+
  scale_color_manual(name="Clusters", values = c("1"="#000000","2"="#D95F02"), 
                     labels=c("1"="Cluster 1", "2"="Cluster 2"))+
  labs(x="PC1 (25.91%)", y="PC2 (10.69%)")+
  scale_y_continuous(breaks=c(-600,-300,0, 300, 600), limits = c(-600, 800))+
  scale_x_continuous(breaks=c(-400,0, 400, 800), limits = c(-410, 1150))+
  guides(color=guide_legend(override.aes = list(size=2),
                            title.position="top",
                            title.hjust = 0.5,
                            nrow = 2, order = 1), 
         shape=guide_legend(override.aes = list(size=2),
                            title.position="top",
                            title.hjust = 0.5,
                            nrow = 3, order = 2)) + #,alpha=guide_legend(nrow = 3, order = 1)
  theme(text = element_text(size=9),
        legend.title=element_text(size=7),
        legend.text=element_text(size=6),
        axis.text.x =element_text(size=9, colour = "black"),
        axis.text.y =element_text(size=9, colour = "black"),
        legend.position="top",
        legend.direction = "horizontal",
        legend.key.size = unit(3,"mm"),
        legend.title.align = 0.5)

# jpeg(file = here("posterPlot/poster_F3.jpeg"),
#      width = 36, height = 14, units = "cm", res = 300)
# theme_set(theme_pubr())
# PCAclassPlot
# dev.off()

print(PCAclassPlot)

plot1 <- ggarrange(PCA408plot_label, 
                  PCAclassPlot,
                  labels = c("A", "B"),
                  ncol = 2, nrow = 1, 
                  widths = c(1,1.1),
                  font.label=list(size = 12, color = "black", face = "bold", family = "Arial"),
                  common.legend = FALSE)


```



# PPT plot 2
## violin plot
```{r}
theme_set(theme_pubr())

outlierDim1Plot_all <- placenta_beta_dim1Top2perc.df_all %>% 
  ggplot(aes(x=OutlierColor, y=value, fill=OutlierColor))+ 
  geom_violin(trim = T)+
  geom_boxplot(width=0.1, fill="white")+
  scale_fill_manual(name="Placenta", 
                    values = c("Outlier"="#1B9E77", "Pure"="#D95F02"),
                    labels = c("Outlier"="Mixed", "Pure"="Pure"))+
  # scale_x_discrete(labels="")+
  labs(x="", y="Beta values")+ #, fill="Placenta"
  stat_compare_means(label = "p.signif", method = "wilcox.test", size = 4) +
  # facet_grid(.~Trimester, scale="free_x")+
  guides(nrow = 1)+
  ggtitle("Overall\nDNA methylation difference")+
  theme(axis.text.y = element_text(size=9, colour ="black"),
        axis.ticks.x= element_blank(),
        axis.text.x=element_blank(),
        legend.title=element_text(size=8),
        legend.text=element_text(size=7),
        legend.key.size = unit(4,"point"),
        plot.title = element_text(hjust = 0.5, size =7),
        axis.title=element_text(size=9, colour ="black"),#,face="bold"
        text = element_text(size=9, colour ="black"),
        legend.position="top")

```

## violin plot ICRs/PMDs

```{r}

theme_set(theme_pubr())
AllPMDsMeanViolinPlot <- ggplot(AllPMDsMeanViolinPlot$data, aes(Outlier, MeanBOfPMD))+ 
  geom_violin(trim = T, aes(fill=Outlier))+ 
  scale_fill_brewer(palette = "Dark2", labels=c("Outlier"="Mixed", "Standard"="Pure"))+
  labs(x="", y="Beta values", fill="Placenta")+
  geom_boxplot(width=0.1, fill="white")+
  stat_compare_means(label = "p.signif", method = "wilcox.test", size = 4) +
  ggtitle("DNA methylation in PMDs")+
  # guides(color=guide_legend(override.aes = list(size=2)))+
  theme(plot.title = element_text(hjust = 0.5, size = 7),
        axis.ticks.x= element_blank(),
        axis.text.x=element_blank(),
        legend.title=element_text(size=7),
        legend.text=element_text(size=6),
        legend.key.size = unit(4,"point"),
        axis.text.y = element_text(size=9, colour ="black"),
        axis.title=element_text(size=9, colour ="black"),#,face="bold"
        text = element_text(size=9, colour ="black"))


allICRsViolinPlot <- ggplot(allICRsViolinPlot$data, aes(Outlier, Betas, fill=Outlier))+ 
  geom_violin(trim = T, aes(fill=Outlier))+ 
  scale_fill_brewer(palette = "Dark2", labels=c("Outlier"="Mixed", "Standard"="Pure"))+
  labs(x="", y="Beta values", fill="Placenta")+
  geom_boxplot(width=0.1, fill="white")+
  stat_compare_means(label = "p.signif", method = "wilcox.test", size = 5) +
  ggtitle("DNA methylation in ICRs")+
  # guides(color=guide_legend(override.aes = list(size=2)))+
  theme(plot.title = element_text(size = 7, hjust = 0.5),
        axis.ticks.x= element_blank(),
        axis.text.x=element_blank(),
        legend.title=element_text(size=7),
        legend.text=element_text(size=6),
        legend.key.size = unit(4,"point"),
        axis.text.y = element_text(size=9, colour ="black"),
        axis.title=element_text(size=9, colour ="black"),#,face="bold"
        text = element_text(size=9, colour ="black"))

plot2 <- ggarrange(outlierDim1Plot_all,
          AllPMDsMeanViolinPlot, 
          allICRsViolinPlot, 
          font.label = list(size = 12, face = "bold", color ="black"),
          nrow = 1, ncol = 3, 
          common.legend = TRUE)


# print(outlierDim1Plot_all)
# print(AllPMDsMeanViolinPlot)
# print(allICRsViolinPlot)
print(plot2)
```

```{r}

PPT <- ggarrange(plot1,
          plot2,
          labels = c("", "C"),
          heights = c(1.2,1),
          font.label = list(size = 12, face = "bold", color ="black"),
          nrow = 2, ncol = 1, 
          common.legend = FALSE)

tiff(file = here("Plots/PPT_F.tiff"),
     width = 14, height = 13, units = "cm", res = 300)
theme_set(theme_pubr())
PPT
dev.off()

print(PPT)

```



