---
title: "technical report (mainly 450k data, 15 GEO data sets used)"
author: "Qianhui"
date: "29/11/2018"
output: html_document
---

This document is mainly for part6 of the GEO data set analysis, that is pull out PC1 probes.

Cord blood only have one sample.


```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.align = "center", error = TRUE, echo = TRUE) # fig.width = 7, 
```


# 1. load data and packages
```{r package, warning=FALSE, message=FALSE}

library(tidyverse)
library(readxl)
library(minfi)
library(magrittr)
library(tibble)
library(data.table)
library(limma)
library(ewastools)
library(ENmix)
library(wateRmelon)
library(WGCNA)
library(impute)
library(missMethyl)
library(FactoMineR)
library(doParallel)
library(ggplot2)
library(RColorBrewer)
pal <- brewer.pal(8, "Dark2")

# GEOmeta, GEO_phenotypes
load(file = "/home/qianhui/DNAme/Process_decidual/RDSfiles/GEOphenoDataAll.RData")

# Join.df_v2, label, GEO_phenotypes_joinedSamples, MDS_joinedSamples
load(file = "/home/qianhui/DNAme/Process_decidual/RDSfiles/GEO_joinedSamples552_Beta_MDS.RData")

# MDSnorm552_Beta, MDSnorm552_M
load(file = "/home/qianhui/DNAme/Process_decidual/RDSfiles/GEO_joinedSamplesNormalised552_BetaM_MDS.RData")

# BMall_combat, MDS_normCorrect552.Beta, MDS_normCorrect552.M
load(file = "/home/qianhui/DNAme/Process_decidual/RDSfiles/GEO_joinedSamples_NormBatchCorrect552_BetaM_MDS.RData")

# MDSnormCali552_Beta, MDSnormCali552_M
load(file = "/home/qianhui/DNAme/Process_decidual/RDSfiles/GEO_joinedSamplesNormalisedCalibrated552_BetaM_MDS.RData")

# annotation needed for using functions
ann450k <- readRDS(file = "/home/qianhui/DNAme/Process_decidual/RDSfiles/ann450k_GEO15sets.rds")
annEPIC <- readRDS(file = "/home/qianhui/DNAme/Process_decidual/RDSfiles/annEPIC_GEO15sets.rds")

```


# subset placenta data and use PCA1
```{r}
registerDoParallel(cores=5)

table(BMall_combat$PhenoData$Sample_name==colnames(BMall_combat$M))
PhenodataPlacenta <- BMall_combat$PhenoData[BMall_combat$PhenoData$Sample%in%"Placenta",]
Placenta_Mnorm_v1 <-  BMall_combat$M[,BMall_combat$PhenoData$Sample%in%"Placenta"]
Placenta_betaNorm <- BMall_combat$Beta[,BMall_combat$PhenoData$Sample%in%"Placenta"]

# check subseted columns are placental samples or not
table(PhenodataPlacenta$Sample_name==colnames(Placenta_Mnorm_v1))

## PCA for normalised M values
PCA_Placenta_M <- FactoMineR::PCA(base::t(Placenta_Mnorm_v1))

### plot eigen values for each PCA
barplot(PCA_Placenta_M$eig[,1], main="Eigenvalues", names.arg=1:nrow(PCA_Placenta_M$eig))
# plot(PCA_Placenta_M,choix="ind")
# calculate correlation for each probe for PCA1 and PCA2
# PCA_Placenta_M_probesSigPCA1and2 <- dimdesc(PCA_Placenta_M, axes =1:2, proba = 0.01)#444312/614861
# saveRDS(PCA_Placenta_M_probesSigPCA1and2, 
# file = "/home/qianhui/DNAme/figures-draftGA-analysis/PCA_Placenta_M_probesCorSigPCA1and2.rds")

```


# the contribution of probes to PC1
```{r Contribution}
# contribution of probs in Dim1
ProbeContrib.df <- PCA_Placenta_M$var$contrib %>% as.data.frame() %>% 
  rownames_to_column(var="Name")
###### quick look at conribution percentages:
summary(ProbeContrib.df)
###### get Dim1 top 2% probes by ordering the contribution percentages of Dim1
ProbeContrib.df.orderedTop2perc <- ProbeContrib.df[base::order(-ProbeContrib.df$Dim.1),] %>% 
   dplyr::slice(1:(0.02*nrow(ProbeContrib.df)))

saveRDS(ProbeContrib.df, 
        file ="/home/qianhui/DNAme/Process_decidual/RDSfiles/Placenta_ProbeContrib.df.rds")
saveRDS(ProbeContrib.df.orderedTop2perc, 
        file ="/home/qianhui/DNAme/Process_decidual/RDSfiles/Placenta_Dim1_top2perc_forOutlierAnalysis.rds")

## plot the last probe in ProbeContrib.df.orderedTop2perc, outliers still have higher DNA meth
# tiff(file = "/home/qianhui/DNAme/Process_decidual/figures/Placenta_ProbeContriTop2perc_egProbe.tiff",
#      width = 20, height = 12, units = "cm", res = 300)
# 
# plot(x=PhenodataPlacenta$, 
#      y=Placenta_betaNorm[rownames(Placenta_betaNorm)%in%ProbeContrib.df.orderedTop2perc$Name[5799],],
#      pch=ifelse(PhenodataPlacenta$Outliers=="Outlier",4,1))
# legend("topright",pch=c(4,1),legend=c("Outlier","Others"), cex=0.8)
# dev.off()

# go/KEGG for probes consistently low in DNA methylation (may be house keeping genes)====
## GO
# Dim1_corSig <- PCA_Placenta_M_probesSigPCA1and2$Dim.1$quanti %>% rownames() #%>% head(5000)
Dim1_top2perc <- ProbeContrib.df.orderedTop2perc$Name

goMeth_Dim1_top2perc <- gometh(sig.cpg = Dim1_top2perc,
                           all.cpg = rownames(Placenta_Mnorm_v1),
                           collection = "GO", array.type = "450K", prior.prob = TRUE, ann=ann450k)

goMeth_Dim1_top2perc[goMeth_Dim1_top2perc$FDR<0.05,] %>% dim()
topGO(goMeth_Dim1_top2perc, number = 20)

saveRDS(goMeth_Dim1_top2perc, 
file = "/home/qianhui/DNAme/Process_decidual/RDSfiles/PlacentaGO_Dim1_top2perc_forOutlierAnalysis.rds")

# ## KEGG
# KEGG_Dim1_top2perc <- gometh(sig.cpg = Dim1_top2perc,
#                            all.cpg = rownames(Placenta_Mnorm_v1),
#                            collection = "KEGG", array.type = "EPIC", prior.prob = TRUE, ann=ann850k)
# 
# KEGG_Dim1_top2perc[KEGG_Dim1_top2perc$FDR<0.05,] %>% dim()
# topKEGG(KEGG_Dim1_top2perc, number = 10)
# 
# saveRDS(KEGG_Dim1_top2perc, 
# file = "/home/qianhui/DNAme/figures-draftGA-analysis/PlacentaKEGG_Dim1_top2perc_forOutlierAnalysis.rds")


# plot Top GO terms
## con30
top2perc_GO <- topGO(goMeth_Dim1_top2perc, number = 20) %>% rownames_to_column(var="GO_ID")
top2perc_GO$Terms <- factor(top2perc_GO$Term, levels = rev(top2perc_GO$Term))

theme_set(theme_bw())
top2perc_GOPlot <- ggplot(top2perc_GO, aes(x= Terms, y= -log10(FDR),fill=Ont)) + 
  geom_bar(stat='identity')+ #"midnightblue"
  scale_fill_hue()+
  coord_flip()+
  geom_hline(yintercept = -log10(0.05), colour="red")+
  labs(x="", y="Enrichment significance (-log10(adusted Pvalue))",fill="GO categories")+
  theme(axis.text.y = element_text(size=10, colour ="black"),
        axis.text.x = element_text(size=10, colour ="black"),
        axis.title=element_text(size=10, colour ="black"),#,face="bold"
        text = element_text(size=10, colour ="black"))

top2perc_GOPlot

tiff(file = "/home/qianhui/DNAme/Process_decidual/figures/Placenta_top2perc_GOPlot_ForOutlier.tiff",
    width = 20, height = 12, units = "cm", res = 300)
top2perc_GOPlot
dev.off()


## plot box plot for beta values of Dim1_top2perc porbes
## manipulate data frames
phenoDataPlacenta.df <- phenoDataPlacenta %>% as.data.frame(stringsAsFactors=FALSE) %>%
  rownames_to_column(var="sampleName") %>% select(c("sampleName", "Outliers"))

placenta_beta_dim1Top2perc <- Placenta_betaNorm[rownames(Placenta_betaNorm)%in%Dim1_top2perc,]
placenta_beta_dim1Top2perc.df <- placenta_beta_dim1Top2perc %>% 
  as.data.frame() %>% rownames_to_column(var="Name") %>% melt(id.var="Name") %>% 
  `colnames<-`(c("Name", "sampleName", "value")) %>% 
  left_join(phenoDataPlacenta.df, by="sampleName")

outlierDim1Plot <- placenta_beta_dim1Top2perc.df %>% 
  ggplot(aes(x=Outliers, y=value))+
  geom_boxplot()+
  scale_x_discrete(labels=c("Outlier"="Outliers", "Standard"="Other Samples"))+
  labs(x="", y="Beta values")+
  theme(axis.text.y = element_text(size=12, colour ="black"),
        axis.text.x = element_text(size=12, colour ="black"),
        axis.title=element_text(size=12, colour ="black"),#,face="bold"
        text = element_text(size=12, colour ="black"))


tiff(file = "/home/qianhui/DNAme/figures-draftGA-analysis/Placenta_Dim1top2percProbePlot_ForOutlier.tiff",
     width = 20, height = 12, units = "cm", res = 300)
theme_set(theme_bw())

outlierDim1Plot
dev.off()



```







