---
title: "Part5_calculateTruningPoint_.Rmd"
author: "Qianhui"
date: "14/04/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.align = "center", error = TRUE, echo = TRUE) # fig.width = 7, 
```

# 1. load data and packages
```{r package, warning=FALSE, message=FALSE}

library(tidyverse)
library(minfi)
library(magrittr)
library(tibble)
library(readxl)
library(doParallel)
library(Gviz)
library(dplyr)
library(reshape2)
library(minfi)
library(plyranges)
library(BSgenome.Hsapiens.UCSC.hg19)
library(TxDb.Hsapiens.UCSC.hg19.knownGene)
library(ggplot2)
library(ggpubr)
library(RColorBrewer)
library(phyloseq)
library(cluster)
pal <- brewer.pal(8, "Dark2")

# GEOmeta, GEO_phenotypes
load(file = "/home/qianhui/DNAme/Process_decidual/RDSfiles/GEO_phenotypes_add10.RData")

# Join.df_v2, GEO_phenotypes_joinedSamples, MDS_joinedSamples
load(file = "/home/qianhui/DNAme/Process_decidual/RDSfiles/GEO_joinedSamples551_Beta_MDS.RData")

# annotation needed for using functions
ann450k <- readRDS(file = "/home/qianhui/DNAme/Process_decidual/RDSfiles/ann450k_GEO15sets.rds")
annEPIC <- readRDS(file = "/home/qianhui/DNAme/Process_decidual/RDSfiles/annEPIC_GEO15sets.rds")

# Residuals, these residuals are Mvalues with control PCA1&2 removed
load(file = "/home/qianhui/DNAme/Process_decidual/RDSfiles/allSamplesResiduals_ControlCorrected.rds")

# BM list after normalisation, but not corrected for batch across samples
NormBMlist <- readRDS(file = "/home/qianhui/DNAme/Process_decidual/RDSfiles/NormBMlist.rds")

# PCA_Placenta_M, PCA_PlacentaT1_M, PCA_PlacentaTerm_M
load(file = "/home/qianhui/DNAme/Process_decidual/RDSfiles/PCA_placenta_deciduals_allT1Term_BMval.RData")


```


# calculate gaps for PC1 of data
```{r, eval=FALSE}


# data("enterotype")

# exord <- ordinate(enterotype, method = "MDS", distance = "jsd")

pam1 = function(x, k){list(cluster = pam(x,k, cluster.only=TRUE))}
# gskmn = clusGap(x[, 1:2], FUN=pam1, K.max = 6, B = 50)

gskmn = clusGap(PCA_Placenta_M$ind$coord[, 1:2], FUN=pam1, K.max = 408, B = 500)
print(gskmn, method="Tibs2001SEmax")
plot_clusgap(gskmn)

```


# calculate IQR for PC1 of data
```{r}

is_outlier <- function(x) {
  return(x < quantile(x, 0.25) - 1.5 * IQR(x) | x > quantile(x, 0.75) + 1.5 * IQR(x))
}


PC1 <- PCA_Placenta_M$ind$coord[, 1] %>% as.data.frame() %>% `colnames<-`("PC1") %>% 
  inset('outlier', value=ifelse(NormBMlist$phenoDataAll$Additional_Info%in%"Outlier", "Outlier", "Pure")) %>% 
  mutate(outlierTF = ifelse(is_outlier(PC1), "TRUE", "FALSE")) %>% 
  mutate(outlierLabel = case_when(
    outlierTF == "TRUE" ~ .$outlier, #[which(.$outlierTF=="TRUE")]
    outlierTF != "TRUE" ~ "NA"))

PC1$outlierLabel[PC1$outlierLabel=="NA"] <- NA

  # mutate(outlierLabel = ifelse(outlierLabel%in%"NA"))
  PC1 %>% ggplot(aes(x=1, y=PC1))+
  geom_boxplot()+
    geom_jitter(aes(color=outlier))+
  geom_text(aes(label = outlierLabel), na.rm = TRUE, hjust = -0.3) #check_overlap = TRUE

# outleir cutoff
quantile(PCA_Placenta_M$ind$coord[, 1], 0.75)+ 1.5*IQR(PCA_Placenta_M$ind$coord[, 1])

```


