---
title: "Information for uploding to GEO (our data set, 10 samples)"
author: "Qianhui"
date: "29/11/2018"
output: html_document
---

This document is mainly for part10 of the GEO data set analysis, that is the normalisation step.


```{r setup, include=FALSE}

knitr::opts_chunk$set(fig.align = "center", error = TRUE, echo = TRUE) # fig.width = 7, 

```


# 1. load data and packages
```{r package, warning=FALSE, message=FALSE, echo=TRUE, results='hide'}

library(tidyverse)
library(readxl)
library(minfi)
library(magrittr)
library(tibble)
library(data.table)
library(limma)
library(ewastools)
library(ENmix)
library(wateRmelon)
library(FactoMineR)
library(WGCNA)
library(impute)
library(ChAMP)
library(sva)
library(quantro)
library(doParallel)
library(ggplot2)
library(RColorBrewer)
pal <- brewer.pal(8, "Dark2")

# GEOmeta, GEO_phenotypes
load(file = "/home/qianhui/DNAme/Process_decidual/RDSfiles/GEO_phenotypes_add10.RData")

# Join.df_v2, Join.df_M_v1, GEO_phenotypes_joinedSamples, MDS_joinedSamples, 
load(file = "/home/qianhui/DNAme/Process_decidual/RDSfiles/GEO_joinedSamples408_Beta_MDS.RData")

PCA_all408_bgCorrected <- readRDS(file = "/home/qianhui/DNAme/Process_decidual/RDSfiles/PCA_all408_bgCorrected.rds")


# GEO_RGset_EPIC_normalPlacenta_ourStudy, GEO_phenoData_EPIC_normalPlacenta_ourStudy
load(file ="/home/qianhui/DNAme/Process_decidual/RDSfiles/GEO_RG&pData_normalPlacenta.RData")

load(file = "/home/qianhui/DNAme/Process_decidual/RDSfiles/MsetsOf9TissueTypes.RData")

# annotation needed for using functions
ann450k <- readRDS(file = "/home/qianhui/DNAme/Process_decidual/RDSfiles/ann450k_GEO15sets.rds")
annEPIC <- readRDS(file = "/home/qianhui/DNAme/Process_decidual/RDSfiles/annEPIC_GEO15sets.rds")

```


# add detection P values for all beta values from our dataset (GSE131945)

## beta values
```{r}


Beta_ourStudy <- wateRmelon::BMIQ(beta.v = Mset_EPIC_normalPlacenta_ourStudy) %>% 
  as.data.frame() %>% rownames_to_column(var="Probe")

detectionP <- minfi::detectionP(GEO_RGset_EPIC_normalPlacenta_ourStudy) %>% 
  `colnames<-`(paste0(colnames(.), "detP")) %>% 
  as.data.frame() %>% rownames_to_column(var="Probe")

# subset
SampleBetaAndDetP <- Beta_ourStudy %>% 
  dplyr::left_join(detectionP, by="Probe") %>% 
  dplyr::select(Probe, `201332340153_R01C01`, `201332340153_R01C01detP`, `201332340153_R03C01`, `201332340153_R03C01detP`, 
                `201414140063_R05C01`, `201414140063_R05C01detP`, `201414140063_R06C01`, `201414140063_R06C01detP`,
                `201414140060_R01C01`, `201414140060_R01C01detP`, `201414140063_R07C01`, `201414140063_R07C01detP`,
                `201414140060_R04C01`, `201414140060_R04C01detP`, `201332340153_R05C01`, `201332340153_R05C01detP`,
                `201332340172_R03C01`, `201332340172_R03C01detP`, `201414140063_R08C01`, `201414140063_R08C01detP`
                )

write_csv(SampleBetaAndDetP, path = "/home/qianhui/DNAme/Process_decidual/RDSfiles/SampleBetaAndDetP.csv")

```


## intensities
```{r}

Mset_EPIC_normalPlacenta_ourStudy <- preprocessRaw(GEO_RGset_EPIC_normalPlacenta_ourStudy)

Meth <- getMeth(Mset_EPIC_normalPlacenta_ourStudy) %>% 
  `colnames<-`(paste0(colnames(.), "Meth")) %>% 
  as.data.frame() %>% rownames_to_column(var="Probe")

UnMeth <- getUnmeth(Mset_EPIC_normalPlacenta_ourStudy) %>% 
  `colnames<-`(paste0(colnames(.), "UnMeth")) %>% 
  as.data.frame() %>% rownames_to_column(var="Probe")

SampleMethAndDetP <- Meth %>% 
  dplyr::left_join(UnMeth, by="Probe") %>% 
  dplyr::left_join(detectionP, by="Probe") %>% 
  dplyr::select(Probe, `201332340153_R01C01UnMeth`, `201332340153_R01C01Meth`, `201332340153_R01C01detP`, 
                `201332340153_R03C01UnMeth`, `201332340153_R03C01Meth`, `201332340153_R03C01detP`, 
                `201414140063_R05C01UnMeth`, `201414140063_R05C01Meth`, `201414140063_R05C01detP`, 
                `201414140063_R06C01UnMeth`, `201414140063_R06C01Meth`, `201414140063_R06C01detP`,
                `201414140060_R01C01UnMeth`, `201414140060_R01C01Meth`, `201414140060_R01C01detP`, 
                `201414140063_R07C01UnMeth`, `201414140063_R07C01Meth`, `201414140063_R07C01detP`,
                `201414140060_R04C01UnMeth`, `201414140060_R04C01Meth`, `201414140060_R04C01detP`, 
                `201332340153_R05C01UnMeth`, `201332340153_R05C01Meth`, `201332340153_R05C01detP`,
                `201332340172_R03C01UnMeth`, `201332340172_R03C01Meth`, `201332340172_R03C01detP`, 
                `201414140063_R08C01UnMeth`, `201414140063_R08C01Meth`, `201414140063_R08C01detP`
                )

write_csv(SampleMethAndDetP, path = "/home/qianhui/DNAme/Process_decidual/RDSfiles/SampleMethAndDetP.csv")

```



