---
title: "Part5_draw Sample Correlation"
author: "Qianhui"
date: "18/01/2019"
output: html_document
---

This document is mainly add to part5 of the GEO data set analysis, draw a sample correlation plot.

```{r setup, include=FALSE}

knitr::opts_chunk$set(fig.align = "center", error = TRUE, echo = TRUE) # fig.width = 7, 

```

# 1. load data and packages
```{r}
library(tidyverse)
library(ggpubr)
library(ggbeeswarm)
library(magrittr)
library(factoextra)
library(Hmisc)
library(corrplot)
library(doParallel)
library(FactoMineR)

# load data residuals
# load(file = "/home/qianhui/DNAme/Process_decidual/RDSfiles/allSamplesResiduals_ControlCorrected.rds")

# BM list after normalisation, but not corrected for batch across samples
NormBMlist <- readRDS(file = "/home/qianhui/DNAme/Process_decidual/RDSfiles/NormBMlist.rds")

## GEOmeta, GEO_phenotypes
load(file = "/home/qianhui/DNAme/Process_decidual/RDSfiles/GEO_phenotypes_add10.RData")

```


# 2. correlation analysis

## use `Hmisc` package to calculate correlation.
```{r eval=FALSE}
registerDoParallel(cores = 10)
# res.dist <- get_dist(t(Residuals), stand = TRUE, method = "pearson")
# fviz_dist(res.dist, gradient = list(low = "#00AFBB", mid = "white", high = "#FC4E07"))
Residuals <- NormBMlist$NormBAll

res2 <- rcorr(Residuals)

# ++++++++++++++++++++++++++++
# flattenCorrMatrix
# ++++++++++++++++++++++++++++
# cormat : matrix of the correlation coefficients
# pmat : matrix of the correlation p-values
flattenCorrMatrix <- function(cormat, pmat) {
  ut <- upper.tri(cormat)
  data.frame(
    row = rownames(cormat)[row(cormat)[ut]],
    column = rownames(cormat)[col(cormat)[ut]],
    cor  =(cormat)[ut],
    p = pmat[ut]
  )
}

CorDF <- flattenCorrMatrix(res2$r, res2$P)

```


## subset values for T1 and term samples, and do correlation calculation
```{r}
# table(colnames(Residuals) %in% GEO_phenotypes$Sample_name)
# Matched_pd <- GEO_phenotypes[match(colnames(Residuals), GEO_phenotypes$Sample_name),]

table(colnames(NormBMlist$NormBAll) %in% NormBMlist$phenoDataAll$Sample_name)
Matched_pd <- NormBMlist$phenoDataAll
Matched_pd$Outlier <- ifelse(Matched_pd$Additional_Info%in%"Outlier",
   # |Matched_pd$Sample_name%in%c("GSM1702177_7970368142_R05C02", "GSM1947213_6008581028_R01C01"),
                             "Outlier", "Standard")
  
# T1
PhenodataPlacentaT1 <- Matched_pd[Matched_pd$Sample%in%"Placenta" & Matched_pd$Trimester%in%"First",]
# Placenta_Mnorm_T1 <-  Residuals[,colnames(Residuals)%in%PhenodataPlacentaT1$Sample_name]
Placenta_Mnorm_T1 <-  NormBMlist$NormMAll[,colnames(NormBMlist$NormMAll)%in%PhenodataPlacentaT1$Sample_name]

## correct batch for T1 placentas
batch <- factor(PhenodataPlacentaT1$Study)
modcombat <- model.matrix(~Outlier, data = PhenodataPlacentaT1)

Placenta_Mnorm_T1_corrected <- sva::ComBat(dat = Placenta_Mnorm_T1,
                                batch = batch, mod = modcombat,
                                par.prior = TRUE, prior.plots=FALSE)

# Placenta_Mnorm_T1_corrected <- Placenta_Mnorm_T1
res_T1 <- cor(Placenta_Mnorm_T1_corrected)
# CorDF_T1 <- flattenCorrMatrix(res_T1$r, res_T1$P) %>% 
#             group_by(row) %>% summarise(corMean=mean(cor))

CorDF_T1 <- res_T1 %>% rowMeans() %>% as.data.frame() %>% rownames_to_column() %>% 
            `colnames<-`(c("SampleNames", "MeanCor")) 

tiff(file = "/home/qianhui/DNAme/Process_decidual/figures/CorrelationPlot_T1_GEOPlacentaSamples.tiff", 
     width = 17, height = 12, units="cm",  res = 300)
corrplot(cor(Placenta_Mnorm_T1_corrected), diag = FALSE, order = "FPC",
         tl.pos = "td", tl.cex = 0.5, method = "color", type = "upper")
dev.off()

corrplot(cor(Placenta_Mnorm_T1_corrected), diag = FALSE, order = "FPC",
         tl.pos = "td", tl.cex = 0.5, method = "color", type = "upper")


# second
PhenodataPlacentaSecond <- Matched_pd[Matched_pd$Sample%in%"Placenta" &Matched_pd$Trimester%in%"Second",] 
Placenta_Mnorm_Second <-  NormBMlist$NormMAll[,colnames(NormBMlist$NormMAll)%in%PhenodataPlacentaSecond$Sample_name]

## correct batch for Term placentas
# batch <- factor(PhenodataPlacentaSecond$Study)
# modcombat <- model.matrix(~Outlier, data = PhenodataPlacentaSecond)
# 
# Placenta_Mnorm_Second_corrected <- sva::ComBat(dat = Placenta_Mnorm_Second,
#                                 batch = batch, mod = modcombat,
#                                 par.prior = TRUE, prior.plots=FALSE)

Placenta_Mnorm_Second_corrected <- Placenta_Mnorm_Second
res_T2 <- cor(Placenta_Mnorm_Second_corrected)

CorDF_T2 <- res_T2 %>% rowMeans() %>% as.data.frame() %>% rownames_to_column() %>% 
            `colnames<-`(c("SampleNames", "MeanCor")) 

corrplot(cor(Placenta_Mnorm_Second_corrected), diag = FALSE, order = "FPC",
         tl.pos = "td", tl.cex = 0.5, method = "color", type = "upper")


# Term
PhenodataPlacentaTerm <- Matched_pd[Matched_pd$Sample%in%"Placenta" &Matched_pd$Trimester%in%"Term",] 
# Placenta_Mnorm_Term <-  Residuals[,colnames(Residuals)%in%PhenodataPlacentaTerm$Sample_name]
Placenta_Mnorm_Term <-  NormBMlist$NormMAll[,colnames(NormBMlist$NormMAll)%in%PhenodataPlacentaTerm$Sample_name]

## correct batch for Term placentas
batch <- factor(PhenodataPlacentaTerm$Study)
modcombat <- model.matrix(~Outlier, data = PhenodataPlacentaTerm)

Placenta_Mnorm_Term_corrected <- sva::ComBat(dat = Placenta_Mnorm_Term,
                                batch = batch, mod = modcombat,
                                par.prior = TRUE, prior.plots=FALSE)

# Placenta_Mnorm_Term_corrected <- Placenta_Mnorm_Term
res_Term <- cor(Placenta_Mnorm_Term_corrected)

# CorDF_Term
CorDF_Term <- res_Term %>% rowMeans() %>% as.data.frame() %>% rownames_to_column() %>% 
            `colnames<-`(c("SampleNames", "MeanCor"))

tiff(file = "/home/qianhui/DNAme/Process_decidual/figures/CorrelationPlot_Term_GEOPlacentaSamples.tiff", 
     width = 17, height = 12, units="cm",  res = 300)
corrplot(cor(Placenta_Mnorm_Term_corrected), diag = FALSE, order = "FPC",
         tl.pos = "td", tl.cex = 0.5, method = "color", type = "upper")
dev.off()

corrplot(cor(Placenta_Mnorm_Term_corrected), diag = FALSE, order = "FPC",
         tl.pos = "td", tl.cex = 0.5, method = "color", type = "upper")

# draw boxplot
CorDFBoxplot <- base::rbind(CorDF_T1, CorDF_T2, CorDF_Term) %>% 
                inset('Trimeter', value=c(rep('First', nrow(CorDF_T1)), 
                                          rep('Second', nrow(CorDF_T2)), 
                                          rep('Term', nrow(CorDF_Term)))) %>% 
                inset('Outlier', value=c(PhenodataPlacentaT1$Outlier, 
                                         PhenodataPlacentaSecond$Outlier,
                                         PhenodataPlacentaTerm$Outlier))

# CorDFBoxplot <- readRDS(file = "/home/qianhui/DNAme/Process_decidual/RDSfiles/CorDFBoxplot.rds")

CorBoxplot <- CorDFBoxplot %>% 
  ggplot(aes(x=Trimeter, y=MeanCor))+
  geom_boxplot(outlier.shape = NA)+
  # geom_dotplot(binaxis = "y", stackdir='center', dotsize=1)
  geom_beeswarm(aes(colour = Outlier), alpha=0.7, cex=0.8, priority = "density")+
  scale_color_brewer(palette = "Dark2", labels=c("Outlier"="Impure", "Standard"="Pure"))+
  labs(y="Correlation", colour="Placenta")+
  # scale_x_discrete(expand = expand_scale(mult = 2))+
  theme(text = element_text(size=9),
        axis.text.x= element_text(size=9, colour = "black"),
        legend.title=element_text(size=9),
        legend.text=element_text(size=9),
        # axis.ticks.x =  = unit(1.5, "cm"),
        legend.position="right")

CorBoxplot

tiff(file = "/home/qianhui/DNAme/Process_decidual/figures/CorrelationBoxplot_T1Term_GEOPlacentaSamples.tiff", 
     width = 20, height = 15, units="cm",  res = 300)
theme_set(theme_pubr())
CorBoxplot
dev.off()

save(Placenta_Mnorm_T1_corrected, Placenta_Mnorm_Term_corrected,
     file = "/home/qianhui/DNAme/Process_decidual/RDSfiles/Placenta_Mnorm_T1Term_corrected_Mval.RData")

# saveRDS(CorDFBoxplot, file = "/home/qianhui/DNAme/Process_decidual/RDSfiles/CorDFBoxplot.rds")
saveRDS(CorBoxplot, file = "/home/qianhui/DNAme/Process_decidual/RDSfiles/Placenta_Mnorm_T1Term_CorBoxplot.rds")

```


## use `corrplot` to draw correlation plot
```{r eval=FALSE}

tiff(file = "/home/qianhui/DNAme/Process_decidual/figures/Beta_density_ggplot_551.tiff", 
     width = 17, height = 12, units="cm",  res = 300)
corrplot(cor(Placenta_Mnorm_Term_corrected), diag = FALSE, order = "FPC",
         tl.pos = "td", tl.cex = 0.5, method = "color", type = "upper")
dev.off()

```


# PCA plot of corrected T1 and Term placenta Mvals

```{r}
# source("~/DNAme/Process_decidual/ggplotPCAFUN.R")
# 
# PCA_Placenta_M_T1 <- FactoMineR::PCA(t(Placenta_Mnorm_T1_corrected))
# 
# ggplotPCA(PCA_Placenta_M = PCA_Placenta_M_T1, 
#           Matched_pd = PhenodataPlacentaT1, 
#           value = "CorrectedM_T1")
# 
# PCA_Placenta_M_Term <- FactoMineR::PCA(t(Placenta_Mnorm_Term_corrected))
# 
# ggplotPCA(PCA_Placenta_M = PCA_Placenta_M_Term, 
#           Matched_pd = PhenodataPlacentaTerm, 
#           value = "CorrectedM_Term")

# residual term
# Placenta_Mnorm_TermPCA_residual <- FactoMineR::PCA(t(Placenta_Mnorm_Term))
# 
# ggplotPCA(PCA_Placenta_M = Placenta_Mnorm_TermPCA_residual, 
#           Matched_pd = PhenodataPlacentaTerm,
#           value = "CorrectedM_residual_Term")  

```



